### PR TITLE
fixed url to sources

### PR DESCRIPTION
**Pull request by mareknovotny**

### CODE REVIEW

**Comment by trollixx** [comment]
I don't see how this fixes anything. The new URL returns 404, while the current one works fine.

**Comment by mareknovotny** [comment]
I had exactly opposite experience 😉
Dne 14. 5. 2016 6:20 dopoledne napsal uživatel "Oleg Shparber" <
notifications@github.com>:

**Comment by trollixx** [comment]
That's strange. What URLs do you see [here](https://github.com/zealdocs/zeal/releases/tag/v0.2.1) in the Downloads section?

**Comment by mareknovotny** [comment]
OK, i don't why but I really had a problem with github redirection before to tag sources, now I tried it once again and it works just fine, so closing this PR

**Pull request closed without merging**
